apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 2 # Số lượng pod chạy
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: ductamhn90/vue-app:latest
          ports:
            - containerPort: 80
